name: retail_sales_dbt
version: "1.0.0"
config-version: 2

profile: retail_sales_dbt

model-paths:
  - models

models:
  retail_sales_dbt:

    staging:
      +materialized: table
      +schema: SILVER

    marts:
      +materialized: table
      +schema: GOLD